name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: protoc
        uses: abelfodil/protoc-action@v1
        with:
          protoc-version: '3.13.0'
          enable-grpc: false
      - run: protoc -Isrc/main/proto src/main/proto/* --go_out=src/main/proto/generated --go-grpc_out=src/main/proto/generated

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
